"unexisting.path": UNEXISTING_VALUE
"database.couchdb.connections[0].password": APP_COUCHDB_DEFAULT_CONNECTION_PASSWORD
"database.couchdb.connections[0].config.retries": APP_COUCHDB_DEFAULT_CONNECTION_RETRIES
"database.couchdb.connections[0].config.keepAlive": APP_COUCHDB_DEFAULT_CONNECTION_KEEP_ALIVE